package com.gsd.sreenidhi.billing;

public class ServiceBillingForm {

	private int ID_SERVICE_BILLING_CYCLE ;
	private String TS_START_DATE_SERVICE_BILLING_CYCLE ;
	private String TS_END_DATE_SERVICE_BILLING_CYCLE ;
	private int FL_COMPLETE_SERVICE_BILLING_CYCLE ;
	private int ID_SERVICE_ENTITLEMENT ;
	private String TX_ENTITLEMENT ;
	private String TS_START_ENTITLEMENT ;
	private String TS_END_ENTITLEMENT ;
	private int FL_ACTIVE_ENTITLEMENT ;
	private int ID_SERVICE_ENTITLEMENT_TYPE ;
	private String TX_ENTITLEMENT_TYPE ;
	private String TX_ENTITLEMENT_TYPE_DESCRIPTION ;
	private int FL_ENTITLEMENT_TYPE_MONTHLY_BILLING ;
	private int ID_ACCOUNT;
	private String TX_EMAIL ;
	private int ID_USER;
	private String TX_FIRSTNAME;
	private String TX_LASTNAME;
	private int ID_SERVICE_TIER_ROLLOVER;
	
	
	public int getID_SERVICE_BILLING_CYCLE() {
		return ID_SERVICE_BILLING_CYCLE;
	}
	public void setID_SERVICE_BILLING_CYCLE(int iD_SERVICE_BILLING_CYCLE) {
		ID_SERVICE_BILLING_CYCLE = iD_SERVICE_BILLING_CYCLE;
	}
	public String getTS_START_DATE_SERVICE_BILLING_CYCLE() {
		return TS_START_DATE_SERVICE_BILLING_CYCLE;
	}
	public void setTS_START_DATE_SERVICE_BILLING_CYCLE(String tS_START_DATE_SERVICE_BILLING_CYCLE) {
		TS_START_DATE_SERVICE_BILLING_CYCLE = tS_START_DATE_SERVICE_BILLING_CYCLE;
	}
	public String getTS_END_DATE_SERVICE_BILLING_CYCLE() {
		return TS_END_DATE_SERVICE_BILLING_CYCLE;
	}
	public void setTS_END_DATE_SERVICE_BILLING_CYCLE(String tS_END_DATE_SERVICE_BILLING_CYCLE) {
		TS_END_DATE_SERVICE_BILLING_CYCLE = tS_END_DATE_SERVICE_BILLING_CYCLE;
	}
	public int getFL_COMPLETE_SERVICE_BILLING_CYCLE() {
		return FL_COMPLETE_SERVICE_BILLING_CYCLE;
	}
	public void setFL_COMPLETE_SERVICE_BILLING_CYCLE(int fL_COMPLETE_SERVICE_BILLING_CYCLE) {
		FL_COMPLETE_SERVICE_BILLING_CYCLE = fL_COMPLETE_SERVICE_BILLING_CYCLE;
	}
	public int getID_SERVICE_ENTITLEMENT() {
		return ID_SERVICE_ENTITLEMENT;
	}
	public void setID_SERVICE_ENTITLEMENT(int iD_SERVICE_ENTITLEMENT) {
		ID_SERVICE_ENTITLEMENT = iD_SERVICE_ENTITLEMENT;
	}
	public String getTX_ENTITLEMENT() {
		return TX_ENTITLEMENT;
	}
	public void setTX_ENTITLEMENT(String tX_ENTITLEMENT) {
		TX_ENTITLEMENT = tX_ENTITLEMENT;
	}
	public String getTS_START_ENTITLEMENT() {
		return TS_START_ENTITLEMENT;
	}
	public void setTS_START_ENTITLEMENT(String tS_START_ENTITLEMENT) {
		TS_START_ENTITLEMENT = tS_START_ENTITLEMENT;
	}
	public String getTS_END_ENTITLEMENT() {
		return TS_END_ENTITLEMENT;
	}
	public void setTS_END_ENTITLEMENT(String tS_END_ENTITLEMENT) {
		TS_END_ENTITLEMENT = tS_END_ENTITLEMENT;
	}
	public int getFL_ACTIVE_ENTITLEMENT() {
		return FL_ACTIVE_ENTITLEMENT;
	}
	public void setFL_ACTIVE_ENTITLEMENT(int fL_ACTIVE_ENTITLEMENT) {
		FL_ACTIVE_ENTITLEMENT = fL_ACTIVE_ENTITLEMENT;
	}
	public int getID_SERVICE_ENTITLEMENT_TYPE() {
		return ID_SERVICE_ENTITLEMENT_TYPE;
	}
	public void setID_SERVICE_ENTITLEMENT_TYPE(int iD_SERVICE_ENTITLEMENT_TYPE) {
		ID_SERVICE_ENTITLEMENT_TYPE = iD_SERVICE_ENTITLEMENT_TYPE;
	}
	public String getTX_ENTITLEMENT_TYPE() {
		return TX_ENTITLEMENT_TYPE;
	}
	public void setTX_ENTITLEMENT_TYPE(String tX_ENTITLEMENT_TYPE) {
		TX_ENTITLEMENT_TYPE = tX_ENTITLEMENT_TYPE;
	}
	public String getTX_ENTITLEMENT_TYPE_DESCRIPTION() {
		return TX_ENTITLEMENT_TYPE_DESCRIPTION;
	}
	public void setTX_ENTITLEMENT_TYPE_DESCRIPTION(String tX_ENTITLEMENT_TYPE_DESCRIPTION) {
		TX_ENTITLEMENT_TYPE_DESCRIPTION = tX_ENTITLEMENT_TYPE_DESCRIPTION;
	}
	public int getFL_ENTITLEMENT_TYPE_MONTHLY_BILLING() {
		return FL_ENTITLEMENT_TYPE_MONTHLY_BILLING;
	}
	public void setFL_ENTITLEMENT_TYPE_MONTHLY_BILLING(int fL_ENTITLEMENT_TYPE_MONTHLY_BILLING) {
		FL_ENTITLEMENT_TYPE_MONTHLY_BILLING = fL_ENTITLEMENT_TYPE_MONTHLY_BILLING;
	}
	public String getTX_EMAIL() {
		return TX_EMAIL;
	}
	public void setTX_EMAIL(String tX_EMAIL) {
		TX_EMAIL = tX_EMAIL;
	}
	public int getID_ACCOUNT() {
		return ID_ACCOUNT;
	}
	public void setID_ACCOUNT(int iD_ACCOUNT) {
		ID_ACCOUNT = iD_ACCOUNT;
	}
	public int getID_USER() {
		return ID_USER;
	}
	public void setID_USER(int iD_USER) {
		ID_USER = iD_USER;
	}
	public String getTX_FIRSTNAME() {
		return TX_FIRSTNAME;
	}
	public void setTX_FIRSTNAME(String tX_FIRSTNAME) {
		TX_FIRSTNAME = tX_FIRSTNAME;
	}
	public String getTX_LASTNAME() {
		return TX_LASTNAME;
	}
	public void setTX_LASTNAME(String tX_LASTNAME) {
		TX_LASTNAME = tX_LASTNAME;
	}
	public int getID_SERVICE_TIER_ROLLOVER() {
		return ID_SERVICE_TIER_ROLLOVER;
	}
	public void setID_SERVICE_TIER_ROLLOVER(int iD_SERVICE_TIER_ROLLOVER) {
		ID_SERVICE_TIER_ROLLOVER = iD_SERVICE_TIER_ROLLOVER;
	}

	
}
